# Generated by Django 2.1.3 on 2018-12-04 02:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('text', models.TextField(blank=True, default='', verbose_name='留言内容')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 12, 4, 2, 50, 51, 441021, tzinfo=utc), verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '留言板内容',
                'db_table': 'message',
                'ordering': ['-create_time'],
            },
        ),
    ]
