# Generated by Django 2.1.3 on 2018-12-05 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20181205_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='回复人姓名')),
                ('text', models.TextField(blank=True, default='', verbose_name='回复内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '回复内容',
                'db_table': 'commit',
                'ordering': ['-create_time'],
            },
        ),
    ]
